# Generated by Django 5.2.4 on 2025-08-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(verbose_name='date created')),
                ('e_date', models.DateTimeField(verbose_name='date last edited')),
                ('src_img', models.FileField(upload_to='', verbose_name='source image')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lon', models.FloatField(verbose_name='longitude')),
                ('crs', models.CharField(max_length=255, verbose_name='coordinate reference system')),
                ('bearing', models.FloatField(default=-1, verbose_name='bearing in degrees from true north')),
                ('marker_text', models.CharField(max_length=510, verbose_name='text')),
            ],
        ),
    ]
