# Generated by Django 5.2.4 on 2025-08-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_markerbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='remark',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='bearing',
            field=models.FloatField(blank=True, null=True, verbose_name='bearing in degrees from true north'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='c_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='e_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date last edited'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='src_img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='source image'),
        ),
    ]
