# Generated by Django 5.2.4 on 2025-08-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_markerbase', '0002_marker_remark_alter_marker_bearing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='bearing',
            field=models.FloatField(blank=True, null=True, verbose_name='bearing in degrees from true north (will auto-fill)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='crs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='coordinate reference system'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude (will auto-fill)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude (will auto-fill)'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='marker_text',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='remark',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
