# Generated by Django 5.2.4 on 2025-08-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_markerbase', '0003_alter_marker_bearing_alter_marker_crs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='bearing',
            field=models.FloatField(blank=True, null=True, verbose_name='bearing'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='src_img',
            field=models.FileField(blank=True, null=True, upload_to='img/', verbose_name='source image'),
        ),
    ]
